# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/tide-jon/.brew/Cellar/cmake/3.21.2/bin/cmake

# The command to remove a file.
RM = /Users/tide-jon/.brew/Cellar/cmake/3.21.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tide-jon/Desktop/github/gomoku

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tide-jon/Desktop/github/gomoku

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/tide-jon/.brew/Cellar/cmake/3.21.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/tide-jon/.brew/Cellar/cmake/3.21.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tide-jon/Desktop/github/gomoku/CMakeFiles /Users/tide-jon/Desktop/github/gomoku//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tide-jon/Desktop/github/gomoku/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/tide-jon/Desktop/github/gomoku/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gomoku

# Build rule for target.
gomoku: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gomoku
.PHONY : gomoku

# fast build rule for target.
gomoku/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/build
.PHONY : gomoku/fast

src/Board.o: src/Board.cpp.o
.PHONY : src/Board.o

# target to build an object file
src/Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Board.cpp.o
.PHONY : src/Board.cpp.o

src/Board.i: src/Board.cpp.i
.PHONY : src/Board.i

# target to preprocess a source file
src/Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Board.cpp.i
.PHONY : src/Board.cpp.i

src/Board.s: src/Board.cpp.s
.PHONY : src/Board.s

# target to generate assembly for a file
src/Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Board.cpp.s
.PHONY : src/Board.cpp.s

src/Gui/AiStats.o: src/Gui/AiStats.cpp.o
.PHONY : src/Gui/AiStats.o

# target to build an object file
src/Gui/AiStats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/AiStats.cpp.o
.PHONY : src/Gui/AiStats.cpp.o

src/Gui/AiStats.i: src/Gui/AiStats.cpp.i
.PHONY : src/Gui/AiStats.i

# target to preprocess a source file
src/Gui/AiStats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/AiStats.cpp.i
.PHONY : src/Gui/AiStats.cpp.i

src/Gui/AiStats.s: src/Gui/AiStats.cpp.s
.PHONY : src/Gui/AiStats.s

# target to generate assembly for a file
src/Gui/AiStats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/AiStats.cpp.s
.PHONY : src/Gui/AiStats.cpp.s

src/Gui/Button.o: src/Gui/Button.cpp.o
.PHONY : src/Gui/Button.o

# target to build an object file
src/Gui/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/Button.cpp.o
.PHONY : src/Gui/Button.cpp.o

src/Gui/Button.i: src/Gui/Button.cpp.i
.PHONY : src/Gui/Button.i

# target to preprocess a source file
src/Gui/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/Button.cpp.i
.PHONY : src/Gui/Button.cpp.i

src/Gui/Button.s: src/Gui/Button.cpp.s
.PHONY : src/Gui/Button.s

# target to generate assembly for a file
src/Gui/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/Button.cpp.s
.PHONY : src/Gui/Button.cpp.s

src/Gui/GUI.o: src/Gui/GUI.cpp.o
.PHONY : src/Gui/GUI.o

# target to build an object file
src/Gui/GUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/GUI.cpp.o
.PHONY : src/Gui/GUI.cpp.o

src/Gui/GUI.i: src/Gui/GUI.cpp.i
.PHONY : src/Gui/GUI.i

# target to preprocess a source file
src/Gui/GUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/GUI.cpp.i
.PHONY : src/Gui/GUI.cpp.i

src/Gui/GUI.s: src/Gui/GUI.cpp.s
.PHONY : src/Gui/GUI.s

# target to generate assembly for a file
src/Gui/GUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/GUI.cpp.s
.PHONY : src/Gui/GUI.cpp.s

src/Gui/GuiBoard.o: src/Gui/GuiBoard.cpp.o
.PHONY : src/Gui/GuiBoard.o

# target to build an object file
src/Gui/GuiBoard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/GuiBoard.cpp.o
.PHONY : src/Gui/GuiBoard.cpp.o

src/Gui/GuiBoard.i: src/Gui/GuiBoard.cpp.i
.PHONY : src/Gui/GuiBoard.i

# target to preprocess a source file
src/Gui/GuiBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/GuiBoard.cpp.i
.PHONY : src/Gui/GuiBoard.cpp.i

src/Gui/GuiBoard.s: src/Gui/GuiBoard.cpp.s
.PHONY : src/Gui/GuiBoard.s

# target to generate assembly for a file
src/Gui/GuiBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/GuiBoard.cpp.s
.PHONY : src/Gui/GuiBoard.cpp.s

src/Gui/GuiPlayer.o: src/Gui/GuiPlayer.cpp.o
.PHONY : src/Gui/GuiPlayer.o

# target to build an object file
src/Gui/GuiPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/GuiPlayer.cpp.o
.PHONY : src/Gui/GuiPlayer.cpp.o

src/Gui/GuiPlayer.i: src/Gui/GuiPlayer.cpp.i
.PHONY : src/Gui/GuiPlayer.i

# target to preprocess a source file
src/Gui/GuiPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/GuiPlayer.cpp.i
.PHONY : src/Gui/GuiPlayer.cpp.i

src/Gui/GuiPlayer.s: src/Gui/GuiPlayer.cpp.s
.PHONY : src/Gui/GuiPlayer.s

# target to generate assembly for a file
src/Gui/GuiPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/GuiPlayer.cpp.s
.PHONY : src/Gui/GuiPlayer.cpp.s

src/Gui/PlayerStats.o: src/Gui/PlayerStats.cpp.o
.PHONY : src/Gui/PlayerStats.o

# target to build an object file
src/Gui/PlayerStats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/PlayerStats.cpp.o
.PHONY : src/Gui/PlayerStats.cpp.o

src/Gui/PlayerStats.i: src/Gui/PlayerStats.cpp.i
.PHONY : src/Gui/PlayerStats.i

# target to preprocess a source file
src/Gui/PlayerStats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/PlayerStats.cpp.i
.PHONY : src/Gui/PlayerStats.cpp.i

src/Gui/PlayerStats.s: src/Gui/PlayerStats.cpp.s
.PHONY : src/Gui/PlayerStats.s

# target to generate assembly for a file
src/Gui/PlayerStats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/PlayerStats.cpp.s
.PHONY : src/Gui/PlayerStats.cpp.s

src/Gui/Text.o: src/Gui/Text.cpp.o
.PHONY : src/Gui/Text.o

# target to build an object file
src/Gui/Text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/Text.cpp.o
.PHONY : src/Gui/Text.cpp.o

src/Gui/Text.i: src/Gui/Text.cpp.i
.PHONY : src/Gui/Text.i

# target to preprocess a source file
src/Gui/Text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/Text.cpp.i
.PHONY : src/Gui/Text.cpp.i

src/Gui/Text.s: src/Gui/Text.cpp.s
.PHONY : src/Gui/Text.s

# target to generate assembly for a file
src/Gui/Text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Gui/Text.cpp.s
.PHONY : src/Gui/Text.cpp.s

src/TranspositionTable.o: src/TranspositionTable.cpp.o
.PHONY : src/TranspositionTable.o

# target to build an object file
src/TranspositionTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/TranspositionTable.cpp.o
.PHONY : src/TranspositionTable.cpp.o

src/TranspositionTable.i: src/TranspositionTable.cpp.i
.PHONY : src/TranspositionTable.i

# target to preprocess a source file
src/TranspositionTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/TranspositionTable.cpp.i
.PHONY : src/TranspositionTable.cpp.i

src/TranspositionTable.s: src/TranspositionTable.cpp.s
.PHONY : src/TranspositionTable.s

# target to generate assembly for a file
src/TranspositionTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/TranspositionTable.cpp.s
.PHONY : src/TranspositionTable.cpp.s

src/algorithm.o: src/algorithm.cpp.o
.PHONY : src/algorithm.o

# target to build an object file
src/algorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/algorithm.cpp.o
.PHONY : src/algorithm.cpp.o

src/algorithm.i: src/algorithm.cpp.i
.PHONY : src/algorithm.i

# target to preprocess a source file
src/algorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/algorithm.cpp.i
.PHONY : src/algorithm.cpp.i

src/algorithm.s: src/algorithm.cpp.s
.PHONY : src/algorithm.s

# target to generate assembly for a file
src/algorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/algorithm.cpp.s
.PHONY : src/algorithm.cpp.s

src/argument_parser.o: src/argument_parser.cpp.o
.PHONY : src/argument_parser.o

# target to build an object file
src/argument_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/argument_parser.cpp.o
.PHONY : src/argument_parser.cpp.o

src/argument_parser.i: src/argument_parser.cpp.i
.PHONY : src/argument_parser.i

# target to preprocess a source file
src/argument_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/argument_parser.cpp.i
.PHONY : src/argument_parser.cpp.i

src/argument_parser.s: src/argument_parser.cpp.s
.PHONY : src/argument_parser.s

# target to generate assembly for a file
src/argument_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/argument_parser.cpp.s
.PHONY : src/argument_parser.cpp.s

src/heuristic.o: src/heuristic.cpp.o
.PHONY : src/heuristic.o

# target to build an object file
src/heuristic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/heuristic.cpp.o
.PHONY : src/heuristic.cpp.o

src/heuristic.i: src/heuristic.cpp.i
.PHONY : src/heuristic.i

# target to preprocess a source file
src/heuristic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/heuristic.cpp.i
.PHONY : src/heuristic.cpp.i

src/heuristic.s: src/heuristic.cpp.s
.PHONY : src/heuristic.s

# target to generate assembly for a file
src/heuristic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/heuristic.cpp.s
.PHONY : src/heuristic.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/misc.o: src/misc.cpp.o
.PHONY : src/misc.o

# target to build an object file
src/misc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/misc.cpp.o
.PHONY : src/misc.cpp.o

src/misc.i: src/misc.cpp.i
.PHONY : src/misc.i

# target to preprocess a source file
src/misc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/misc.cpp.i
.PHONY : src/misc.cpp.i

src/misc.s: src/misc.cpp.s
.PHONY : src/misc.s

# target to generate assembly for a file
src/misc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/misc.cpp.s
.PHONY : src/misc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gomoku"
	@echo "... src/Board.o"
	@echo "... src/Board.i"
	@echo "... src/Board.s"
	@echo "... src/Gui/AiStats.o"
	@echo "... src/Gui/AiStats.i"
	@echo "... src/Gui/AiStats.s"
	@echo "... src/Gui/Button.o"
	@echo "... src/Gui/Button.i"
	@echo "... src/Gui/Button.s"
	@echo "... src/Gui/GUI.o"
	@echo "... src/Gui/GUI.i"
	@echo "... src/Gui/GUI.s"
	@echo "... src/Gui/GuiBoard.o"
	@echo "... src/Gui/GuiBoard.i"
	@echo "... src/Gui/GuiBoard.s"
	@echo "... src/Gui/GuiPlayer.o"
	@echo "... src/Gui/GuiPlayer.i"
	@echo "... src/Gui/GuiPlayer.s"
	@echo "... src/Gui/PlayerStats.o"
	@echo "... src/Gui/PlayerStats.i"
	@echo "... src/Gui/PlayerStats.s"
	@echo "... src/Gui/Text.o"
	@echo "... src/Gui/Text.i"
	@echo "... src/Gui/Text.s"
	@echo "... src/TranspositionTable.o"
	@echo "... src/TranspositionTable.i"
	@echo "... src/TranspositionTable.s"
	@echo "... src/algorithm.o"
	@echo "... src/algorithm.i"
	@echo "... src/algorithm.s"
	@echo "... src/argument_parser.o"
	@echo "... src/argument_parser.i"
	@echo "... src/argument_parser.s"
	@echo "... src/heuristic.o"
	@echo "... src/heuristic.i"
	@echo "... src/heuristic.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/misc.o"
	@echo "... src/misc.i"
	@echo "... src/misc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/tide-jon/Desktop/github/gomoku/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

